/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehicleMatcherRouteImport } from './routes/vehicle-matcher'
import { Route as SmartLocatorRouteImport } from './routes/smart-locator'
import { Route as FleetPortalRouteImport } from './routes/fleet-portal'
import { Route as FleetDashboardRouteImport } from './routes/fleet-dashboard'
import { Route as BridyAiRouteImport } from './routes/bridy-ai'
import { Route as AdminIntelligenceRouteImport } from './routes/admin-intelligence'
import { Route as IndexRouteImport } from './routes/index'

const VehicleMatcherRoute = VehicleMatcherRouteImport.update({
  id: '/vehicle-matcher',
  path: '/vehicle-matcher',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartLocatorRoute = SmartLocatorRouteImport.update({
  id: '/smart-locator',
  path: '/smart-locator',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetPortalRoute = FleetPortalRouteImport.update({
  id: '/fleet-portal',
  path: '/fleet-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetDashboardRoute = FleetDashboardRouteImport.update({
  id: '/fleet-dashboard',
  path: '/fleet-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BridyAiRoute = BridyAiRouteImport.update({
  id: '/bridy-ai',
  path: '/bridy-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntelligenceRoute = AdminIntelligenceRouteImport.update({
  id: '/admin-intelligence',
  path: '/admin-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-intelligence': typeof AdminIntelligenceRoute
  '/bridy-ai': typeof BridyAiRoute
  '/fleet-dashboard': typeof FleetDashboardRoute
  '/fleet-portal': typeof FleetPortalRoute
  '/smart-locator': typeof SmartLocatorRoute
  '/vehicle-matcher': typeof VehicleMatcherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-intelligence': typeof AdminIntelligenceRoute
  '/bridy-ai': typeof BridyAiRoute
  '/fleet-dashboard': typeof FleetDashboardRoute
  '/fleet-portal': typeof FleetPortalRoute
  '/smart-locator': typeof SmartLocatorRoute
  '/vehicle-matcher': typeof VehicleMatcherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-intelligence': typeof AdminIntelligenceRoute
  '/bridy-ai': typeof BridyAiRoute
  '/fleet-dashboard': typeof FleetDashboardRoute
  '/fleet-portal': typeof FleetPortalRoute
  '/smart-locator': typeof SmartLocatorRoute
  '/vehicle-matcher': typeof VehicleMatcherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-intelligence'
    | '/bridy-ai'
    | '/fleet-dashboard'
    | '/fleet-portal'
    | '/smart-locator'
    | '/vehicle-matcher'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-intelligence'
    | '/bridy-ai'
    | '/fleet-dashboard'
    | '/fleet-portal'
    | '/smart-locator'
    | '/vehicle-matcher'
  id:
    | '__root__'
    | '/'
    | '/admin-intelligence'
    | '/bridy-ai'
    | '/fleet-dashboard'
    | '/fleet-portal'
    | '/smart-locator'
    | '/vehicle-matcher'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminIntelligenceRoute: typeof AdminIntelligenceRoute
  BridyAiRoute: typeof BridyAiRoute
  FleetDashboardRoute: typeof FleetDashboardRoute
  FleetPortalRoute: typeof FleetPortalRoute
  SmartLocatorRoute: typeof SmartLocatorRoute
  VehicleMatcherRoute: typeof VehicleMatcherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicle-matcher': {
      id: '/vehicle-matcher'
      path: '/vehicle-matcher'
      fullPath: '/vehicle-matcher'
      preLoaderRoute: typeof VehicleMatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-locator': {
      id: '/smart-locator'
      path: '/smart-locator'
      fullPath: '/smart-locator'
      preLoaderRoute: typeof SmartLocatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet-portal': {
      id: '/fleet-portal'
      path: '/fleet-portal'
      fullPath: '/fleet-portal'
      preLoaderRoute: typeof FleetPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet-dashboard': {
      id: '/fleet-dashboard'
      path: '/fleet-dashboard'
      fullPath: '/fleet-dashboard'
      preLoaderRoute: typeof FleetDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridy-ai': {
      id: '/bridy-ai'
      path: '/bridy-ai'
      fullPath: '/bridy-ai'
      preLoaderRoute: typeof BridyAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-intelligence': {
      id: '/admin-intelligence'
      path: '/admin-intelligence'
      fullPath: '/admin-intelligence'
      preLoaderRoute: typeof AdminIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminIntelligenceRoute: AdminIntelligenceRoute,
  BridyAiRoute: BridyAiRoute,
  FleetDashboardRoute: FleetDashboardRoute,
  FleetPortalRoute: FleetPortalRoute,
  SmartLocatorRoute: SmartLocatorRoute,
  VehicleMatcherRoute: VehicleMatcherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
